require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RelationshipsController do

  # This should return the minimal set of attributes required to create a valid
  # Relationship. As you add validations to Relationship, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { parent_id: 1, child_id: 2 } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RelationshipsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Relationship" do
        expect {
          post :create, {:relationship => valid_attributes}, valid_session
        }.to change(Relationship, :count).by(1)
      end

      it "assigns a newly created relationship as @relationship" do
        post :create, {:relationship => valid_attributes}, valid_session
        assigns(:relationship).should be_a(Relationship)
        assigns(:relationship).should be_persisted
      end

      it "redirects to the created relationship" do
        post :create, {:relationship => valid_attributes}, valid_session
        response.should redirect_to(Relationship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved relationship as @relationship" do
        # Trigger the behavior that occurs when invalid params are submitted
        Relationship.any_instance.stub(:save).and_return(false)
        post :create, {:relationship => { "parent_id" => "invalid value" }}, valid_session
        assigns(:relationship).should be_a_new(Relationship)
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested relationship" do
      relationship = Relationship.create! valid_attributes
      expect {
        delete :destroy, {:id => relationship.to_param}, valid_session
      }.to change(Relationship, :count).by(-1)
    end

    it "redirects to the relationships list" do
      relationship = Relationship.create! valid_attributes
      delete :destroy, {:id => relationship.to_param}, valid_session
      response.should redirect_to(relationships_url)
    end
  end

end
